depth_image_topic: /XTION/depth/image 
camera_info_topic: /XTION/depth/camera_info 
#source: /home/mwuethri_local/data/projects/coordinate_particle_filter/evaluation/moving_boxes/sim/dataset
source: camera
evaluation_count: 100 #the number of evaluations

object_names: [
 impact_battery
]








sampling_blocks: [
 [ 0,  1,  2,  3,  4,  5]
]

max_kl_divergence: 2.0
use_gpu: false

# filtering parameters ----------------------------------------------------------------------
downsampling_factor: 8 #8
initial_sample_count: 1000 #10000 this is the number of samples for the initialization
max_sample_count: 10000 #10000 this is for the gpu to allocate memory

linear_acceleration_sigma:   0.2 #0.1  0.2  1.0 2.0
angular_acceleration_sigma: 3.0 #1.5  3.0  15.0 30.0
damping: 5.0 #5.0  20.0  1000.0 1000.0

# observation model parameters --------------------------------------------------------------
tail_weight: 0.01 #0.01, 0.998
model_sigma: 0.003 #0.003, 0.005
sigma_factor: 0.0014247 #0.0014247

# occlusion process model 
initial_occlusion_prob: 0.1 #0.1
p_occluded_visible: 0.1 #0.1
p_occluded_occluded: 0.7 #0.7

min_delta_time: 0.




