
gaussian_filter:
  update_rate: 1.0

  unscented_transform:
    alpha: 1.0

  object_transition:
    linear_sigma: 0.002
    angular_sigma: 0.01
    velocity_factor: 0.8

  observation:
    fg_noise_std: 0.001

    # uniform tail arguments
    tail_weight: 0.1
    uniform_tail_min: -5000.0
    uniform_tail_max: 5000.0

    bg_depth: -3.0
    bg_noise_std: 100.0

  object_color:
   R: 97
   G: 117
   B: 123

# object colors
gt_color_r: 97
gt_color_g: 117
gt_color_b: 123
belief_color_r: 250
belief_color_g: 232
belief_color_b: 184

